#!/usr/bin/env python3
"""生成知识库 INDEX.md — CI 用脚本。

探索 KB 仓库目录结构，调用 LLM 生成 INDEX.md 导航指南。
本地交互使用 /generate-index skill，CI 使用本脚本。

用法:
  python scripts/generate_index.py kb/kb-redis-docs

环境变量:
  INDEX_GEN_PROVIDER: openai (默认)
  INDEX_GEN_MODEL: deepseek-chat (默认)
  INDEX_GEN_BASE_URL: https://api.deepseek.com (默认)
  INDEX_GEN_API_KEY: API key (必需)
"""

import argparse
import logging
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger(__name__)


def explore_repo(kb_path: str) -> str:
    """探索 KB 仓库，返回结构化描述。"""
    root = Path(kb_path)
    docs_root = None

    # 找到 docs 根目录
    for candidate in [root / "docs", root]:
        if candidate.is_dir() and list(candidate.glob("*/_index.md")):
            docs_root = candidate
            break

    if docs_root is None:
        # 尝试更深一层
        for d in root.rglob("_index.md"):
            docs_root = d.parent.parent
            break

    if docs_root is None:
        raise ValueError(f"找不到文档根目录: {kb_path}")

    lines = []
    lines.append(f"# KB Repo: {kb_path}")
    lines.append(f"# Docs root: {docs_root}")
    lines.append("")

    # 统计总文件数
    all_md = list(docs_root.rglob("*.md"))
    lines.append(f"Total .md files: {len(all_md)}")
    lines.append("")

    # 顶层目录统计
    lines.append("## Top-level directories:")
    top_dirs = sorted([d for d in docs_root.iterdir() if d.is_dir()])
    for d in top_dirs:
        count = len(list(d.rglob("*.md")))
        lines.append(f"  {d.name}/ ({count} files)")

        # 二级目录
        sub_dirs = sorted([sd for sd in d.iterdir() if sd.is_dir()])
        for sd in sub_dirs:
            sub_count = len(list(sd.rglob("*.md")))
            if sub_count > 0:
                lines.append(f"    {sd.name}/ ({sub_count} files)")
    lines.append("")

    # 检测版本目录
    import re
    version_pattern = re.compile(r'^\d+\.\d+')
    lines.append("## Version directories:")
    for d in docs_root.rglob("*"):
        if d.is_dir() and version_pattern.match(d.name):
            parent_rel = d.parent.relative_to(docs_root)
            count = len(list(d.rglob("*.md")))
            lines.append(f"  {parent_rel}/{d.name}/ ({count} files)")
    lines.append("")

    # 读取关键 _index.md 文件
    lines.append("## Key _index.md contents:")
    index_files = sorted(docs_root.glob("*/_index.md"))
    # 也读二级
    index_files += sorted(docs_root.glob("*/*/_index.md"))

    for idx_file in index_files[:20]:  # 限制数量
        rel = idx_file.relative_to(docs_root)
        content = idx_file.read_text(errors="replace")
        # 只取 frontmatter + 前 500 字符
        if len(content) > 800:
            content = content[:800] + "\n... (truncated)"
        lines.append(f"\n### {rel}")
        lines.append(content)

    return "\n".join(lines)


SYSTEM_PROMPT = """You are a technical documentation analyst. Generate an INDEX.md file for a knowledge base repository.

The INDEX.md serves as a navigation guide for an AI search agent. It should be:
- Concise (3-5KB)
- Actionable: "if question is about X, search in Y/"
- Accurate: based only on the repo structure provided
- Written for an AI agent, not a human reader"""

USER_PROMPT_TEMPLATE = """Based on this repository structure analysis, generate an INDEX.md file.

{repo_analysis}

Generate the INDEX.md with these sections:
1. **Overview**: source, doc count, language, generation date
2. **Directory Map**: table with path, topic, doc count, description (for both top-level areas)
3. **Version Strategy**: which areas have versions, which is latest, search rules (default to non-versioned)
4. **Topic Routing**: table mapping question types to search paths
5. **Excluded Paths**: version directories to skip during indexing
6. **Answer Rules**: citation format, version handling, Hugo shortcode notes

Use markdown tables. Be precise with directory names and file counts.
Start with: # <KB Name> — Search Index Guide
Include a note that this was generated by /generate-index.

Output ONLY the markdown content, no code fences."""


def generate_index(kb_path: str) -> str:
    """探索仓库并调用 LLM 生成 INDEX.md。"""
    log.info(f"📂 探索仓库: {kb_path}")
    repo_analysis = explore_repo(kb_path)
    log.info(f"📊 分析完成: {len(repo_analysis)} 字符")

    # LLM 调用
    provider = os.environ.get("INDEX_GEN_PROVIDER", "openai")
    model = os.environ.get("INDEX_GEN_MODEL", "deepseek-chat")
    base_url = os.environ.get("INDEX_GEN_BASE_URL", "https://api.deepseek.com")
    api_key = os.environ.get("INDEX_GEN_API_KEY", "")

    if not api_key:
        raise ValueError("INDEX_GEN_API_KEY 环境变量未设置")

    from openai import OpenAI
    client = OpenAI(api_key=api_key, base_url=base_url)

    log.info(f"🤖 调用 LLM: {model} @ {base_url}")
    prompt = USER_PROMPT_TEMPLATE.format(repo_analysis=repo_analysis)

    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        max_tokens=4096,
        temperature=0,
    )

    return resp.choices[0].message.content


def main() -> None:
    parser = argparse.ArgumentParser(description="生成知识库 INDEX.md")
    parser.add_argument("kb_path", help="KB 仓库路径 (e.g., kb/kb-redis-docs)")
    parser.add_argument("--dry-run", action="store_true", help="只输出不写文件")
    args = parser.parse_args()

    content = generate_index(args.kb_path)

    if args.dry_run:
        print(content)
    else:
        output = os.path.join(args.kb_path, "INDEX.md")
        with open(output, "w") as f:
            f.write(content)
        log.info(f"✅ 写入 {output} ({len(content)} 字符)")


if __name__ == "__main__":
    main()
